import shutil
shutil.move("build/asset-manifest.json", ".")
shutil.move("build/favicon.png", ".")
shutil.move("build/index.html", ".")
shutil.move("build/manifest.json", ".")
shutil.move("build/precache-manifest.99ac1f98e3ecda5c658c86e62d008363.js", ".")
shutil.move("build/robots.txt", ".")
shutil.move("build/service-worker.js", ".")
shutil.move("build/static", ".")
